attire:
  active: Fútbol de robots
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: |
    <category name="Comandos comunes">
        <block type="RepeticionSimple"></block>
        <block type="RepeticionCondicional"></block>
    </category>
    <category name="Expresiones comunes">
        <block type="math_number"></block>
        <block type="DireccionSelector"></block>
    </category>
    <category name="Operaciones de Fútbol">
        <block type="MoverAlBetoAl_"></block>
        <block type="PatearAlArco"></block>
        <block type="CambiarAlBetoDeFila"></block>
        <block type="estáLaPelotaEnEstaCelda"></block>
        <block type="estáElBetoEnElInicioDeLaFila"></block>
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturnnoparams"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.65  
name: Fútbol de robots 