attire:
  active: Cartas, letras y numeros
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: |
    <category name="Comandos de palos y valores">
        <block type="DecirPalo_"></block>
        <block type="DecirNúmero_"></block>
    </category>
    <category name="Expresiones de palos y valores">
        <block type="palo_"></block>
        <block type="valorDeCartaEspañolaDe40_"></block>
    </category>
    <category name="Expresiones de cartas">
        <block type="cartaTapada"></block>
        <block type="dameElPalo_"></block>
        <block type="dameElValor_"></block>
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturnnoparams"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.65  
name: Descubrir la carta