name: Cartas, letras y números
rules:
  - { image: FlechaIzquierda.png,       when: { blue:  10, black:   0, red: 10, green: 0 } } 
  - { image: FlechaDerecha.png,         when: { blue:  10, black:   0, red: 20, green: 0 } } 
  - { image: 0.png,                     when: { blue:   1, black:   0, red:  0, green: 0 } } 
  - { image: 1.png,                     when: { blue:   1, black:   1, red:  0, green: 0 } } 
  - { image: 2.png,                     when: { blue:   1, black:   2, red:  0, green: 0 } } 
  - { image: 3.png,                     when: { blue:   1, black:   3, red:  0, green: 0 } } 
  - { image: 4.png,                     when: { blue:   1, black:   4, red:  0, green: 0 } } 
  - { image: 5.png,                     when: { blue:   1, black:   5, red:  0, green: 0 } } 
  - { image: 6.png,                     when: { blue:   1, black:   6, red:  0, green: 0 } } 
  - { image: 7.png,                     when: { blue:   1, black:   7, red:  0, green: 0 } } 
  - { image: 8.png,                     when: { blue:   1, black:   8, red:  0, green: 0 } } 
  - { image: 9.png,                     when: { blue:   1, black:   9, red:  0, green: 0 } } 
  - { image: Espacio.png,               when: { blue:   2, black:  10, red:  0, green: 0 } } 
  - { image: A.png,                     when: { blue:   2, black:  11, red:  0, green: 0 } } 
  - { image: B.png,                     when: { blue:   2, black:  12, red:  0, green: 0 } } 
  - { image: C.png,                     when: { blue:   2, black:  13, red:  0, green: 0 } } 
  - { image: D.png,                     when: { blue:   2, black:  14, red:  0, green: 0 } } 
  - { image: E.png,                     when: { blue:   2, black:  15, red:  0, green: 0 } } 
  - { image: F.png,                     when: { blue:   2, black:  16, red:  0, green: 0 } } 
  - { image: G.png,                     when: { blue:   2, black:  17, red:  0, green: 0 } } 
  - { image: H.png,                     when: { blue:   2, black:  18, red:  0, green: 0 } } 
  - { image: I.png,                     when: { blue:   2, black:  19, red:  0, green: 0 } } 
  - { image: J.png,                     when: { blue:   2, black:  20, red:  0, green: 0 } } 
  - { image: K.png,                     when: { blue:   2, black:  21, red:  0, green: 0 } } 
  - { image: L.png,                     when: { blue:   2, black:  22, red:  0, green: 0 } } 
  - { image: M.png,                     when: { blue:   2, black:  23, red:  0, green: 0 } } 
  - { image: N.png,                     when: { blue:   2, black:  24, red:  0, green: 0 } } 
  - { image: ENIE.png,                  when: { blue:   2, black:  25, red:  0, green: 0 } } 
  - { image: O.png,                     when: { blue:   2, black:  26, red:  0, green: 0 } } 
  - { image: P.png,                     when: { blue:   2, black:  27, red:  0, green: 0 } } 
  - { image: Q.png,                     when: { blue:   2, black:  28, red:  0, green: 0 } } 
  - { image: R.png,                     when: { blue:   2, black:  29, red:  0, green: 0 } } 
  - { image: S.png,                     when: { blue:   2, black:  30, red:  0, green: 0 } } 
  - { image: T.png,                     when: { blue:   2, black:  31, red:  0, green: 0 } } 
  - { image: U.png,                     when: { blue:   2, black:  32, red:  0, green: 0 } } 
  - { image: V.png,                     when: { blue:   2, black:  33, red:  0, green: 0 } } 
  - { image: W.png,                     when: { blue:   2, black:  34, red:  0, green: 0 } } 
  - { image: X.png,                     when: { blue:   2, black:  35, red:  0, green: 0 } } 
  - { image: Y.png,                     when: { blue:   2, black:  36, red:  0, green: 0 } } 
  - { image: Z.png,                     when: { blue:   2, black:  37, red:  0, green: 0 } } 
  - { image: Reverso.png,               when: { blue:   3, black: '*', red:  1, green: 0 } } 
  - { image: Bastos-01.png,             when: { blue:   3, black: 101, red:  0, green: 0 } } 
  - { image: Bastos-02.png,             when: { blue:   3, black: 102, red:  0, green: 0 } } 
  - { image: Bastos-03.png,             when: { blue:   3, black: 103, red:  0, green: 0 } } 
  - { image: Bastos-04.png,             when: { blue:   3, black: 104, red:  0, green: 0 } } 
  - { image: Bastos-05.png,             when: { blue:   3, black: 105, red:  0, green: 0 } } 
  - { image: Bastos-06.png,             when: { blue:   3, black: 106, red:  0, green: 0 } } 
  - { image: Bastos-07.png,             when: { blue:   3, black: 107, red:  0, green: 0 } } 
  - { image: Bastos-10.png,             when: { blue:   3, black: 110, red:  0, green: 0 } } 
  - { image: Bastos-11.png,             when: { blue:   3, black: 111, red:  0, green: 0 } } 
  - { image: Bastos-12.png,             when: { blue:   3, black: 112, red:  0, green: 0 } } 
  - { image: Copas-01.png,              when: { blue:   3, black: 201, red:  0, green: 0 } } 
  - { image: Copas-02.png,              when: { blue:   3, black: 202, red:  0, green: 0 } } 
  - { image: Copas-03.png,              when: { blue:   3, black: 203, red:  0, green: 0 } } 
  - { image: Copas-04.png,              when: { blue:   3, black: 204, red:  0, green: 0 } } 
  - { image: Copas-05.png,              when: { blue:   3, black: 205, red:  0, green: 0 } } 
  - { image: Copas-06.png,              when: { blue:   3, black: 206, red:  0, green: 0 } } 
  - { image: Copas-07.png,              when: { blue:   3, black: 207, red:  0, green: 0 } } 
  - { image: Copas-10.png,              when: { blue:   3, black: 210, red:  0, green: 0 } } 
  - { image: Copas-11.png,              when: { blue:   3, black: 211, red:  0, green: 0 } } 
  - { image: Copas-12.png,              when: { blue:   3, black: 212, red:  0, green: 0 } } 
  - { image: Espadas-01.png,            when: { blue:   3, black: 301, red:  0, green: 0 } } 
  - { image: Espadas-02.png,            when: { blue:   3, black: 302, red:  0, green: 0 } } 
  - { image: Espadas-03.png,            when: { blue:   3, black: 303, red:  0, green: 0 } } 
  - { image: Espadas-04.png,            when: { blue:   3, black: 304, red:  0, green: 0 } } 
  - { image: Espadas-05.png,            when: { blue:   3, black: 305, red:  0, green: 0 } } 
  - { image: Espadas-06.png,            when: { blue:   3, black: 306, red:  0, green: 0 } } 
  - { image: Espadas-07.png,            when: { blue:   3, black: 307, red:  0, green: 0 } } 
  - { image: Espadas-10.png,            when: { blue:   3, black: 310, red:  0, green: 0 } } 
  - { image: Espadas-11.png,            when: { blue:   3, black: 311, red:  0, green: 0 } } 
  - { image: Espadas-12.png,            when: { blue:   3, black: 312, red:  0, green: 0 } } 
  - { image: Oros-01.png,               when: { blue:   3, black: 401, red:  0, green: 0 } } 
  - { image: Oros-02.png,               when: { blue:   3, black: 402, red:  0, green: 0 } } 
  - { image: Oros-03.png,               when: { blue:   3, black: 403, red:  0, green: 0 } } 
  - { image: Oros-04.png,               when: { blue:   3, black: 404, red:  0, green: 0 } } 
  - { image: Oros-05.png,               when: { blue:   3, black: 405, red:  0, green: 0 } } 
  - { image: Oros-06.png,               when: { blue:   3, black: 406, red:  0, green: 0 } } 
  - { image: Oros-07.png,               when: { blue:   3, black: 407, red:  0, green: 0 } } 
  - { image: Oros-10.png,               when: { blue:   3, black: 410, red:  0, green: 0 } } 
  - { image: Oros-11.png,               when: { blue:   3, black: 411, red:  0, green: 0 } } 
  - { image: Oros-12.png,               when: { blue:   3, black: 412, red:  0, green: 0 } } 
  - { image: Iluminada-Espadas-01.png,  when: { blue:   3, black: 101, red:  0, green: 1 } } 
  - { image: Iluminada-Espadas-02.png,  when: { blue:   3, black: 102, red:  0, green: 1 } } 
  - { image: Iluminada-Espadas-03.png,  when: { blue:   3, black: 103, red:  0, green: 1 } } 
  - { image: Iluminada-Espadas-04.png,  when: { blue:   3, black: 104, red:  0, green: 1 } } 
  - { image: Iluminada-Espadas-05.png,  when: { blue:   3, black: 105, red:  0, green: 1 } } 
  - { image: Iluminada-Espadas-06.png,  when: { blue:   3, black: 106, red:  0, green: 1 } } 
  - { image: Iluminada-Espadas-07.png,  when: { blue:   3, black: 107, red:  0, green: 1 } } 
  - { image: Iluminada-Espadas-10.png,  when: { blue:   3, black: 110, red:  0, green: 1 } } 
  - { image: Iluminada-Espadas-11.png,  when: { blue:   3, black: 111, red:  0, green: 1 } } 
  - { image: Iluminada-Espadas-12.png,  when: { blue:   3, black: 112, red:  0, green: 1 } } 
  - { image: Iluminada-Oros-01.png,     when: { blue:   3, black: 201, red:  0, green: 1 } } 
  - { image: Iluminada-Oros-02.png,     when: { blue:   3, black: 202, red:  0, green: 1 } } 
  - { image: Iluminada-Oros-03.png,     when: { blue:   3, black: 203, red:  0, green: 1 } } 
  - { image: Iluminada-Oros-04.png,     when: { blue:   3, black: 204, red:  0, green: 1 } } 
  - { image: Iluminada-Oros-05.png,     when: { blue:   3, black: 205, red:  0, green: 1 } } 
  - { image: Iluminada-Oros-06.png,     when: { blue:   3, black: 206, red:  0, green: 1 } } 
  - { image: Iluminada-Oros-07.png,     when: { blue:   3, black: 207, red:  0, green: 1 } } 
  - { image: Iluminada-Oros-10.png,     when: { blue:   3, black: 210, red:  0, green: 1 } } 
  - { image: Iluminada-Oros-11.png,     when: { blue:   3, black: 211, red:  0, green: 1 } } 
  - { image: Iluminada-Oros-12.png,     when: { blue:   3, black: 212, red:  0, green: 1 } } 
  - { image: Iluminada-Bastos-01.png,   when: { blue:   3, black: 301, red:  0, green: 1 } } 
  - { image: Iluminada-Bastos-02.png,   when: { blue:   3, black: 302, red:  0, green: 1 } } 
  - { image: Iluminada-Bastos-03.png,   when: { blue:   3, black: 303, red:  0, green: 1 } } 
  - { image: Iluminada-Bastos-04.png,   when: { blue:   3, black: 304, red:  0, green: 1 } } 
  - { image: Iluminada-Bastos-05.png,   when: { blue:   3, black: 305, red:  0, green: 1 } } 
  - { image: Iluminada-Bastos-06.png,   when: { blue:   3, black: 306, red:  0, green: 1 } } 
  - { image: Iluminada-Bastos-07.png,   when: { blue:   3, black: 307, red:  0, green: 1 } } 
  - { image: Iluminada-Bastos-10.png,   when: { blue:   3, black: 310, red:  0, green: 1 } } 
  - { image: Iluminada-Bastos-11.png,   when: { blue:   3, black: 311, red:  0, green: 1 } } 
  - { image: Iluminada-Bastos-12.png,   when: { blue:   3, black: 312, red:  0, green: 1 } } 
  - { image: Iluminada-Copas-01.png,    when: { blue:   3, black: 401, red:  0, green: 1 } } 
  - { image: Iluminada-Copas-02.png,    when: { blue:   3, black: 402, red:  0, green: 1 } } 
  - { image: Iluminada-Copas-03.png,    when: { blue:   3, black: 403, red:  0, green: 1 } } 
  - { image: Iluminada-Copas-04.png,    when: { blue:   3, black: 404, red:  0, green: 1 } } 
  - { image: Iluminada-Copas-05.png,    when: { blue:   3, black: 405, red:  0, green: 1 } } 
  - { image: Iluminada-Copas-06.png,    when: { blue:   3, black: 406, red:  0, green: 1 } } 
  - { image: Iluminada-Copas-07.png,    when: { blue:   3, black: 407, red:  0, green: 1 } } 
  - { image: Iluminada-Copas-10.png,    when: { blue:   3, black: 410, red:  0, green: 1 } } 
  - { image: Iluminada-Copas-11.png,    when: { blue:   3, black: 411, red:  0, green: 1 } } 
  - { image: Iluminada-Copas-12.png,    when: { blue:   3, black: 412, red:  0, green: 1 } } 
