name: Sudoku simplificado
attire:
  active: 'Cartas, letras y números'
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: |
    <category name="Comandos básicos">
        <block type="MoverSiPuede_"></block>
        <block type="RepeticionSimple"></block>
        <block type="AlternativaSimple"></block>
    </category>
    <category name="Expresiones básicas">
        <block type="math_number"></block>
        <block type="DireccionSelector"></block>
        <block type="OperadorDeComparacion"></block>
        <block type="OperadorLogico"></block>
        <block type="not"></block>
    </category>
    <category name="Operaciones de números">
        <block type="PonerDígito_"></block>
        <block type="hayDígito"></block>
        <block type="dígitoEnLaPrimeraPosiciónDeLaFila"></block>
        <block type="dígitoEnLaSegundaPosiciónDeLaFila"></block>
        <block type="dígitoEnLaTerceraPosiciónDeLaFila"></block>
        <block type="dígitoEnLaPrimeraPosiciónDeLaColumna"></block>
        <block type="dígitoEnLaSegundaPosiciónDeLaColumna"></block>
        <block type="dígitoEnLaTerceraPosiciónDeLaColumna"></block>
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Mis funciones" custom="FUNCTION_CALLS">  </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturn"></block>
        <block type="procedures_defreturnsimplewithparams"></block>
    </category>
    <category name="Eventos">
        <block type="InteractiveLetterBinding"></block>
        <block type="InteractiveNumberBinding"></block>
        <block type="InteractiveKeyBinding"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
source:
  visible: true
  percentage: 0.80    
library:
  visible: false