attire:
  active: La cena de Dino
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: | 
    <category name="Comandos b치sicos">
        <block type="MoverADinoAl_"></block>
        <block type="CambiarADinoDeFila"></block>
        <block type="RechazarLaComida"></block>
        <block type="ComerLaHamburguesa"></block>
        <block type="ComerLaTorta"></block>
        <block type="ComerElBife"></block>
        <block type="ComerElDurazno"></block>
        <block type="RepeticionSimple"></block>
        <block type="AlternativaSimple"></block>
        <block type="AlternativaCompleta"></block>
        <block type="RepeticionCondicional"></block>
    </category>
    <category name="Expresiones b치sicas">
        <block type="math_number"></block>
        <block type="DireccionSelector"></block>
        <block type="OperadorLogico"></block>
        <block type="not"></block>
        <block type="est치DinoEnElInicioDeLaFila"></block>
        <block type="hayHamburguesa"></block>
        <block type="hayTorta"></block>
        <block type="hayBife"></block>
        <block type="hayDurazno"></block>
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Mis funciones" custom="FUNCTION_CALLS">        </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturnnoparams"></block>
        <block type="procedures_defreturnsimple"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
name: Est치 lista la cena