name: La música del loro
rules:
  - { image: Fondo.png                  , when: { black: 0, blue: 0, green: 0, red: 0 } }
  - { image: Loro.png                   , when: { black: 0, blue: 1, green: 0, red: 0 } }
  - { image: Tambor.png                 , when: { black: 0, blue: 0, green: 1, red: 0 } }
  - { image: LoroYTambor.png            , when: { black: 0, blue: 1, green: 1, red: 0 } }
  - { image: Guitarra.png               , when: { black: 1, blue: 0, green: 0, red: 0 } }
  - { image: LoroYGuitarra.png          , when: { black: 1, blue: 1, green: 0, red: 0 } }
  - { image: ComenzoElShowDeTambor.png  , when: { black: 0, blue: 1, green: 1, red: 1 } }
  - { image: ComenzoElShowDeGuitarra.png, when: { black: 1, blue: 1, green: 0, red: 1 } }
