attire:
  active: 'Cartas, letras y números'
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  defaultToolbox: |
    <category name="Comandos básicos">
        <block type="Poner__Veces"></block>
        <block type="Sacar__Veces"></block>
        <block type="Mover__Veces"></block>
        <block type="SacarTodas"></block>
        <block type="SacarTodas_"></block>
        <block type="IrAlBorde"></block>
        <block type="IrAlOrigen"></block>
        <block type="PasarASiguientePosición"></block>
        <block type="BOOM"></block>
        <block type="RepeticionSimple"></block>
        <block type="AlternativaCompleta"></block>
        <block type="RepeticionCondicional"></block>
        <block type="Asignacion"></block>
    </category>
    <category name="Expresiones básicas">
        <block type="math_number"></block>
        <block type="ColorSelector"></block>
        <block type="DireccionSelector"></block>
        <block type="nroBolitas"></block>
        <block type="puedeMover"></block>
        <block type="OperadorNumerico"></block>
        <block type="OperadorDeComparacion"></block>
        <block type="OperadorLogico"></block>
        <block type="not"></block>
    </category>
    <category name="Operaciones de Números">
        <block type="númeroActual"></block>
        <block type="númeroOculto"></block>
        <block type="PonerNúmero_"></block>
        <block type="SacarNúmeroActual"></block>
        <block type="OcultarNúmeroActual"></block>
        <block type="RevelarNúmeroActual"></block>
        <block type="hayNúmero"></block>
        <block type="hayNúmeroNoOculto"></block>
        <block type="hayNúmeroOculto"></block>
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Mis funciones" custom="FUNCTION_CALLS">  </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturn"></block>
        <block type="procedures_defreturnsimplewithparams"></block>
        <block type="procedures_defreturn"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: true
  visible_edition: true
execution_speed:
  active: superhigh
  user_permissions:
    can_change_speed: true
library:
  visible: false
name: Test números
source:
  visible: true
  percentage: 0.90
