name: Ordenamiento en bambalinas
attire:
  active: 'Cartas, letras y números'
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: |
    <category name="Comandos básicos">
        <block type="RepeticionCondicional"></block>
        <block type="Asignacion"></block>
    </category>
    <category name="Expresiones básicas">
        <block type="not"></block>
    </category>
    <category name="Operaciones de cartas">
        <block type="IrALaCartaMásChicaSinOrdenar"></block>
        <block type="SacarCartaActual"></block>
        <block type="IrALaPróximaPosiciónParaBajarCarta"></block>
        <block type="PonerCarta_"></block>
        <block type="quedanCartasSinOrdenar"></block>
        <block type="cartaActual"></block>
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Mis funciones" custom="FUNCTION_CALLS">  </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturn"></block>
        <block type="procedures_defreturnsimplewithparams"></block>
        <block type="procedures_defreturn"></block>
    </category>
board:
  active: 1
  initial_board_source: selected
  visible_edition: true
  collapse_toolbox: false
  user_permissions:
    can_view_attire_section: false
    can_edit_board: false
    can_change_initial_board: true
    can_change_initial_board_source: false
    can_view_size_section: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
source:
  visible: true
  percentage: 0.7
library:
  visible: false
