attire:
  active: 'Cartas, letras, números'
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: | 
    <category name="Comandos básicos">
        <block type="PasarASiguientePosición"></block>
    </category>
    <category name="Expresiones de palos y valores">
        <block type="palo_"></block>
        <block type="valorDeCartaEspañolaDe40_"></block>
    </category>
    <category name="Comandos de Cartas">
        <block type="PonerCarta_"></block>
    </category>
    <category name="Expresiones de Cartas">
        <block type="dameCarta__"></block>
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturnnoparams"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
name: Quiero retruco
