name: Lucho y las luces
rules:
  - { image: Lucho.png           , when: {     black: 2,  blue: 0,  green: 0,  red: 0 } }
  - { image: FondoLucho.png      , when: {     black: 0,  blue: 0,  green: 0,  red: 0 } }
  - { image: LuchoLuzApagada.png , when: {     black: 2,  blue: 0,  green: 1,  red: 0 } }
  - { image: LuzApagada.png      , when: {     black: 0,  blue: 0,  green: 1,  red: 0 } }
  - { image: LuchoLuzApagada.png , when: {     black: 2,  blue: 1,  green: 0,  red: 1 } }
  - { image: LuzApagada.png      , when: {     black: 0,  blue: 1,  green: 0,  red: 1 } }
  - { image: LuchoLuzPrendida.png, when: {     black: 2,  blue: 1,  green: 0,  red: 0 } }
  - { image: LuzPrendida.png     , when: {     black: 0,  blue: 1,  green: 0,  red: 0 } }
  - { image: Lucho.png           , when: {     black: 3,  blue: 0,  green: 0,  red: 0 } }
  - { image: FondoLucho.png      , when: {     black: 1,  blue: 0,  green: 0,  red: 0 } }
