name: Memotest
attire:
  active: 'Cartas, letras y números'
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: |
    <category name="Comandos básicos">
        <block type="MoverSiPuede_"></block>
        <block type="PasarASiguientePosición"></block>
        <block type="AlternativaSimple"></block>
        <block type="RepeticionCondicional"></block>
        <block type="Asignacion"></block>
    </category>
    <category name="Expresiones básicas">
        <block type="DireccionSelector"></block>
        <block type="OperadorDeComparacion"></block>
        <block type="OperadorLogico"></block>
    </category>
    <category name="Operaciones de cartas">
        <block type="cartaActual"></block>
        <block type="dameElPalo_"></block>
        <block type="dameElNúmero_"></block>
        <block type="DarVueltaLaCartaActual"></block>
        <block type="IluminarLaCartaActual"></block>
        <block type="hayCartaTapada"></block>
        <block type="hayCartaDestapadaSinIluminar"></block>
        <block type="hayOtraCartaDestapadaSinIluminar"></block>
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Mis funciones" custom="FUNCTION_CALLS">  </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturn"></block>
        <block type="procedures_defreturnsimplewithparams"></block>
        <block type="InteractiveKeyBinding"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
source:
  visible: true
  percentage: 1    
library:
  visible: false