name: Dino y la comida
rules:
  - { image: Fondo.png           , when: { black: 0, blue: 0, green: 0, red: 0 } }
  - { image: Dino.png            , when: { black: 0, blue: 1, green: 0, red: 0 } }
  - { image: DinoYHamburguesa.png, when: { black: 0, blue: 1, green: 0, red: 1 } }
  - { image: DinoYTorta.png      , when: { black: 0, blue: 1, green: 0, red: 2 } }
  - { image: DinoYBife.png       , when: { black: 0, blue: 1, green: 1, red: 0 } }
  - { image: DinoYFruta.png      , when: { black: 0, blue: 1, green: 2, red: 0 } }
  - { image: Hamburguesa.png     , when: { black: 0, blue: 0, green: 0, red: 1 } }
  - { image: Torta.png           , when: { black: 0, blue: 0, green: 0, red: 2 } }
  - { image: Bife.png            , when: { black: 0, blue: 0, green: 1, red: 0 } }
  - { image: Fruta.png           , when: { black: 0, blue: 0, green: 2, red: 0 } }
