attire:
  active: Memotest
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  disabled:
  visible:
    - Mover
    - IrAlBorde
    - Procedimientos primitivos
    - Mis procedimientos
    - RepeticionSimple
    - RepeticionCondicional
    - AlternativaSimple
    - AlternativaCompleta
    - Asignacion
    - Mis funciones
    - Direccion
    - Numero
    - OperadorNumerico
    - OperadorDeComparacion
    - OperadorDeNegacion
    - OperadorLogico
    - DefinicionDeProcedimientoParametrizado
    - DefinicionDeFuncionSimpleParametrizada
    - DefinicionDeProgramaInteractivo
    - DefinicionDeAsociacionDeTeclaEspecial
    - DefinicionDeAsociacionDeTeclaNúmero
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: true
    can_edit_board: true
  visible_edition: true
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
name: Memotest
